version: 2.1

orbs:
  codecov: codecov/codecov@volatile

executors:
  default:
    docker:
      - image: circleci/golang:1.14-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout

      - run: make check-style

  test_backend:
    executor:
      name: default
    steps:

      - checkout

      - run: go get -v -t -d ./...
      - run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...

      - codecov/upload:
          file: "coverage.txt"
          flags: "backend"

  deploy:
    executor:
      name: default
    environment:
      MM_SERVICESETTINGS_SITEURL: http://134.122.71.100:8065
      MM_ADMIN_USERNAME: gtsut16@freeuni.edu.ge
      MM_ADMIN_PASSWORD: buJg#4V1g*
    steps:

      - checkout
      - run: make deploy
        
  test_frontend:
    executor:
      name: default
    steps:

      - checkout

      - run: cd webapp && npm install
      - run: cd webapp && npm run test

      - codecov/upload:
          file: "webapp/coverage/lcov.info"
          flags: "frontend"

workflows:
  version: 2
  build-deploy:
    jobs:
      - lint
      - test_backend
      - test_frontend
      - deploy:
          requires:
            - test_frontend
            - test_backend